Runtime Error
Error: ./src/app/results/page.tsx:84:14
Ecmascript file had an error
  82 |
  83 | // Metadata can still be defined for server-rendered part of the page
> 84 | export const metadata = {
     |              ^^^^^^^^
  85 |   title: 'Sınav Sonucu | SınavMaster',
  86 |   description: 'Sınav sonucunuzu ve kazandığınız ödülü görüntüleyin.',
  87 | };

You are attempting to export "metadata" from a component marked with "use client", which is disallowed. Either remove the export, or the "use client" directive. Read more: https://nextjs.org/docs/app/api-reference/directives/use-client